USE UTN_DB;

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (1, 'Matemática I', 1);

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (2, 'Programación I', 1);

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (3, 'Base de Datos', 2);

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (4, 'Organización de Computadoras', 2);

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (5, 'Matemática II', 3);

INSERT INTO MATERIA (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (6, 'Programación II', 3);